TOP = ../..
include $(TOP)/configure/CONFIG

DIRS += edl
ADL_DIR = adl
UI_DIR  = ui/autoconvert
EDL_DIR = edl/autoconvert
OPI_DIR = opi/autoconvert

include $(TOP)/configure/RULES_DIRS

-include $(SUPPORT)/configure/RULES_OPI
